### ISSUE TITLE
Decoding with LM

### ISSUE THREAD

**Issue by sharmaannapurna** [cwig/start_follow_read#11]
Hi,
Please share the pointers to create the following files related to language model:
fst_path: "../hwn5-comp-2017/data/comp_lm/data/graph/HCLG.fst"
mdl_path: "../hwn5-comp-2017/data/comp_lm/data/lang_test/basic.mdl"
words_path: "../hwn5-comp-2017/data/comp_lm/data/graph/words.txt"
phones_path: "../hwn5-comp-2017/data/comp_lm/data/lang_test/phones.txt"

I installed Pykaldi but not able to make out where to generate these files for my dataset.
Thanks in advance.

**Comment by arthureffting** [comment]
Hello @sharmaannapurna, did you find out how to do this? I would also be interested.

**Comment by sharmaannapurna** [comment]
Hi @arthureffting , I could not continue with Kaldi model. I modified the code to work with a language model generated using KenLM.
