### ISSUE TITLE
Extract Text-lines only

### ISSUE THREAD

**Issue by mrocr** [cwig/start_follow_read#4]
@cwig @ctensmeyer @herobd
In case I only want to extract Text-lines without the hwr step, how can I do that?
Perhaps only output a Page xml file?

**Comment by herobd** [comment]
The forward function in e2e/e2e_model.py returns the start-of-line points and line-follower points, which you could convert to the format you need. You'd just comment out the HWR stuff if you don't want it.

You can see these points being accessed in run_hwr.py https://github.com/cwig/start_follow_read/blob/e9a4f7cb92a63e803c958239be4b907f35efa346/run_hwr.py#L96
